export const MODULES = [
  {
    id: 1, module: "01", title: "Market Structure", level: "Beginner", tag: "ICT",
    lessons: 6, duration: "48 min", emoji: "📊", image: "/modules/module-01.webp",
    desc: "The foundation of everything — how price creates trends, breaks structure, and signals reversals.",
    topics: ["HH/HL & LH/LL", "Break of Structure (BOS)", "Change of Character (ChoCH/MSS)", "CISD — Change in State of Delivery", "STH / ITH / LTH Advanced Structure", "Weekly Market Rhythm"],
  },
  {
    id: 2, module: "02", title: "Liquidity Concepts", level: "Beginner", tag: "ICT",
    lessons: 5, duration: "45 min", emoji: "💧", image: "/modules/module-02.webp",
    desc: "Study how ICT-style liquidity concepts interpret stop locations, liquidity pools, and potential sweeps; these are framework-based interpretations, not verified explanations of every move.",
    topics: ["Buy-Side & Sell-Side Liquidity", "Equal Highs & Equal Lows (EQH/EQL)", "Internal vs External Range Liquidity", "Liquidity Sweep vs Liquidity Run", "HRLR vs LRLR"],
  },
  {
    id: 3, module: "03", title: "Fair Value Gaps (FVG)", level: "Beginner", tag: "ICT & SMC",
    lessons: 5, duration: "42 min", emoji: "🎯", image: "/modules/module-03.webp",
    desc: "Study 3-candle price imbalances, their common interpretations, and how traders test them as potential entry zones.",
    topics: ["FVG Formation (BISI & SIBI)", "Consequent Encroachment (CE)", "1st Presented FVG", "Inversion FVG (IFVG)", "Balanced Price Range (BPR)", "RDRB"],
  },
  {
    id: 4, module: "07", title: "Order Blocks", level: "Intermediate", tag: "ICT",
    lessons: 6, duration: "52 min", emoji: "🧱", image: "/modules/module-04.webp",
    desc: "A framework for studying areas where significant buying or selling may have occurred and how price may react; the underlying orders and intent cannot be confirmed from a chart alone.",
    topics: ["Bullish & Bearish OBs", "Breaker Blocks", "Mitigation Blocks", "Rejection Blocks", "Reclaimed OBs (2024)", "Suspension Block (2025)"],
  },
  {
    id: 5, module: "08", title: "Killzones & Macro Times", level: "Intermediate", tag: "ICT",
    lessons: 4, duration: "38 min", emoji: "⏰", image: "/modules/module-05.webp",
    desc: "Study ICT session timing, macro windows, and how traders incorporate time of day into their analysis.",
    topics: ["Asian / London / NY Killzones", "London Close", "8 Macro Time Windows", "Silver Bullet Hours", "CBDR & Asian Range"],
  },
  {
    id: 6, module: "09", title: "Power of Three (AMD)", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "44 min", emoji: "🔱", image: "/modules/module-06.webp",
    desc: "Study the Accumulation, Manipulation, Distribution (AMD) framework and how traders use it to structure a daily narrative.",
    topics: ["AMD Daily Framework", "Judas Swing", "Daily Candle Reading", "Weekly AMD Cycle", "Monthly PO3"],
  },
  {
    id: 7, module: "10", title: "Premium & Discount", level: "Intermediate", tag: "ICT",
    lessons: 4, duration: "36 min", emoji: "📐", image: "/modules/module-07.webp",
    desc: "Study premium and discount ranges, equilibrium, OTE, and how traders use them to frame potential entries.",
    topics: ["Premium vs Discount Zones", "Equilibrium (50%)", "OTE — Optimal Trade Entry (62-79%)", "PD Array Matrix", "How to Draw the Range"],
  },
  {
    id: 8, module: "11", title: "ICT Entry Models", level: "Intermediate", tag: "ICT",
    lessons: 7, duration: "60 min", emoji: "🎲", image: "/modules/module-08.webp",
    desc: "Structured ICT entry-model frameworks, including Silver Bullet, 2022 Model, Unicorn, and others; test their conditions and outcomes rather than treating them as guaranteed setups.",
    topics: ["Silver Bullet Model", "2022 ICT Model", "Unicorn Model", "One Shot One Kill", "IOFED Model", "5-Minute Entry Drill"],
  },
  {
    id: 9, module: "26", title: "Market Maker Models", level: "Advanced", tag: "ICT",
    lessons: 5, duration: "55 min", emoji: "🏦", image: "/modules/module-09.webp",
    desc: "Study the MMBM and MMSM frameworks and how ICT teachings model multi-day price behavior; the actual positions or intentions of banks cannot be confirmed from charts alone.",
    topics: ["Market Maker Buy Model (MMBM)", "Market Maker Sell Model (MMSM)", "False Flag", "Seek & Destroy Friday", "TGIF Pattern"],
  },
  {
    id: 10, module: "27", title: "SMT Divergence", level: "Advanced", tag: "ICT",
    lessons: 4, duration: "40 min", emoji: "🔀", image: "/modules/module-10.webp",
    desc: "Study SMT divergence between correlated markets as a possible confirmation or context signal; divergence does not by itself establish institutional activity or predict the next move.",
    topics: ["SMT Between Correlated Pairs", "Intermarket SMT", "SMT with Indices", "SMT Entry Confirmation", "Daily vs Intraday SMT"],
  },
  {
    id: 11, module: "28", title: "IPDA & CRT", level: "Advanced", tag: "ICT",
    lessons: 5, duration: "50 min", emoji: "🤖", image: "/modules/module-11.webp",
    desc: "Study IPDA, weekly draws and Candle Range Theory as theoretical ICT frameworks for analyzing time and price behavior; they should not be treated as a verified market algorithm.",
    topics: ["IPDA — Interbank Price Delivery Algorithm", "20/40/60 Day Lookback", "NWOG & NDOG Gaps", "Candle Range Theory (CRT)", "Weekly Draw on Liquidity"],
  },
  {
    id: 12, module: "29", title: "ICT Mentorship — Newer Concepts", level: "Advanced", tag: "NEWER",
    lessons: 8, duration: "75 min", emoji: "🆕", image: "/modules/module-12.webp",
    desc: "Newer ICT concepts including the Venom Model, Propulsion Blocks, Quarterly Shifts, and related mentorship updates.",
    topics: ["Venom Model", "Propulsion Block", "Quarterly Shift", "SCOB — Silver Bullet Order Block", "QML — Quasi Market Level", "Weekly Profile Templates"],
  },
  {
    id: 13, module: "25", title: "SMC — Smart Money Concepts", level: "SMC", tag: "SMC",
    lessons: 6, duration: "50 min", emoji: "💼", image: "/modules/module-13.webp",
    desc: "A broad community framework overlapping with ICT terminology—structure, OBs, FVGs, and CHoCH—presented with explicit, testable definitions.",
    topics: ["SMC vs ICT Differences", "Supply & Demand Zones", "SMC Order Blocks", "SMC ChoCH & BOS", "Inducement", "SMC Trade Framework"],
  },
  {
    id: 14, module: "12", title: "Top-Down Analysis", level: "Intermediate", tag: "ICT & SMC",
    lessons: 5, duration: "45 min", emoji: "🔭", image: "/modules/module-14.webp",
    desc: "The complete multi-timeframe methodology — from Monthly bias to 1-minute entry precision.",
    topics: ["Monthly / Weekly Bias", "Daily Narrative Building", "4H Confirmation", "15M & 5M Entry Timeframe", "Full Trade Walkthrough"],
  },

  // ─── NEW MODULES (15–28) ───────────────────────────────────────────────────
  {
    id: 15, module: "13", title: "Daily Bias Framework", level: "Intermediate", tag: "ICT",
    lessons: 6, duration: "54 min", emoji: "🧭", image: "/modules/module-15.webp",
    desc: "A key decision in many trading approaches — determining directional bias before price moves and building a narrative to guide entries.",
    topics: ["What Daily Bias Actually Means", "HTF Context → Daily Narrative", "Previous Day High / Low Logic", "Midnight Open & True Day High/Low", "Session Bias Alignment", "When to Flip Bias Mid-Day"],
    isNew: true,
  },
  {
    id: 16, module: "14", title: "Draw on Liquidity", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "48 min", emoji: "🎯", image: "/modules/module-16.webp",
    desc: "Study Draw on Liquidity (DOL), external and internal range liquidity, and how traders identify potential targets.",
    topics: ["What is the Draw on Liquidity (DOL)", "Identifying the Next Likely Target", "ERL vs IRL — External vs Internal Range Liquidity", "DOL on Multiple Timeframes", "Trading With the Draw vs Against It", "DOL and PD Array Confluence"],
    isNew: true,
  },
  {
    id: 17, module: "15", title: "Dealing Ranges & PD Arrays", level: "Intermediate", tag: "ICT",
    lessons: 6, duration: "52 min", emoji: "📦", image: "/modules/module-17.webp",
    desc: "Study the PD Array framework and how traders compare potential zones for entries and targets.",
    topics: ["What is a Dealing Range", "Full PD Array Matrix — All 12 Arrays Ranked", "Breaker vs Mitigation vs Order Block Priority", "IFVG as a PD Array", "Nested Dealing Ranges", "How to Stack PD Arrays for Confluence"],
    isNew: true,
  },
  {
    id: 18, module: "30", title: "Institutional Order Flow", level: "Advanced", tag: "ICT",
    lessons: 7, duration: "65 min", emoji: "🏛️", image: "/modules/module-18.webp",
    desc: "How ICT-style frameworks interpret accumulation, manipulation, and distribution when studying price behavior often described as institutional-scale delivery; these interpretations should be tested rather than treated as direct evidence of institutional activity.",
    topics: ["Institutional vs Retail Order Flow", "How ICT frameworks model institutional positioning", "Stop-hunt / liquidity-sweep narratives", "Candle patterns sometimes interpreted as institutional activity", "Displacement and directional interpretation", "Testing interpretations of institutional intent from price structure", "Order Flow Confirmation Before Entry"],
    isNew: true,
  },
  {
    id: 19, module: "04", title: "Session Timing & Market Hours", level: "Beginner", tag: "ICT",
    lessons: 5, duration: "40 min", emoji: "🕐", image: "/modules/module-19.webp",
    desc: "ICT teaching places strong emphasis on time-of-day context. Session timing can be useful for organizing analysis, but market behavior and liquidity vary by instrument and day.",
    topics: ["The Four Trading Sessions", "Asian Session — Range Building", "London Session — Manipulation & Displacement", "New York AM — Primary Distribution", "London Close & NY PM Reversal Logic", "DST Changes and Session Shifts"],
    isNew: true,
  },
  {
    id: 20, module: "31", title: "Narrative Building", level: "Advanced", tag: "ICT",
    lessons: 8, duration: "72 min", emoji: "📖", image: "/modules/module-20.webp",
    desc: "Learn to build a multi-timeframe trading narrative from higher-timeframe context to execution.",
    topics: ["What is a Trading Narrative", "Monthly → Weekly → Daily Alignment", "Building the Daily Story from Midnight Open", "Session-Level Narrative Construction", "When the Narrative Fails — Invalidation Logic", "Narrative vs Indicators", "Full Walkthrough: Building a Trade from Scratch", "Backtesting Your Narrative Framework"],
    isNew: true,
  },
  {
    id: 21, module: "32", title: "Quarterly Theory & Seasonal Tendencies", level: "Advanced", tag: "ICT",
    lessons: 5, duration: "50 min", emoji: "📅", image: "/modules/module-21.webp",
    desc: "Study quarterly theory and seasonal tendencies as contextual tools for forming a market narrative.",
    topics: ["Quarterly Market Profiles", "Q1: Seasonal Tendencies & Accumulation Narratives", "Q2: Seasonal Tendencies & Manipulation Narratives", "Q3: Seasonal Tendencies & Distribution Narratives", "Q4: Year-End Positioning & Reversal Narratives", "Monthly Seasonal Tendencies by Pair"],
    isNew: true,
  },
  {
    id: 22, module: "16", title: "Liquidity Voids & Gaps", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "44 min", emoji: "🕳️", image: "/modules/module-22.webp",
    desc: "Understanding voids, gaps, and inefficiencies and how traders study price reactions around them.",
    topics: ["Liquidity Voids vs Fair Value Gaps", "Weekend Gaps (NWOG & NDOG)", "Opening Gaps as Draw on Liquidity", "Void Fill Patterns — Full vs Partial", "Inversion of Gaps After Fill", "Trading Into and Out of Voids"],
    isNew: true,
  },
  {
    id: 23, module: "33", title: "Time & Price Theory", level: "Advanced", tag: "ICT",
    lessons: 6, duration: "58 min", emoji: "⏳", image: "/modules/module-23.webp",
    desc: "Study the relationship between time windows and price locations and how traders incorporate both into analysis.",
    topics: ["The Time-Price Matrix", "Macro Time Windows (8 precise windows)", "Price Delivery at Specific Times", "Time-Based Reversals", "The 20-Minute Rule", "Studying Time-Based Price Behavior"],
    isNew: true,
  },
  {
    id: 24, module: "17", title: "Turtle Soup & Liquidity-Sweep Frameworks", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "42 min", emoji: "🐢", image: "/modules/module-24.webp",
    desc: "A reversal pattern in ICT that studies false breakouts, liquidity sweeps, and potential reversals.",
    topics: ["What is Turtle Soup — The Origin", "Engineering the Stop Hunt", "Identifying the Setup: EQH/EQL as Bait", "Entry Logic After the Sweep", "Turtle Soup on Multiple Timeframes", "Common Errors That Kill the Trade"],
    isNew: true,
  },
  {
    id: 25, module: "18", title: "Judas Swing & AMD Deep Dive", level: "Intermediate", tag: "ICT",
    lessons: 6, duration: "55 min", emoji: "🎭", image: "/modules/module-25.webp",
    desc: "Study the Judas Swing as a false-move concept within AMD and how traders test it across sessions.",
    topics: ["The Judas Swing — What It Is and Why It Exists", "London Judas Swing Anatomy", "NY AM Judas Swing Patterns", "How Far the Manipulation Extends", "Confirming Judas vs Real Breakout", "Entries After Judas Completion"],
    isNew: true,
  },
  {
    id: 26, module: "34", title: "Balanced Price Range (BPR)", level: "Advanced", tag: "ICT",
    lessons: 4, duration: "36 min", emoji: "⚖️", image: "/modules/module-26.webp",
    desc: "A reaction zone in ICT where bullish and bearish FVGs overlap; study how traders use the area as potential confluence.",
    topics: ["BPR Formation — Bullish FVG meets Bearish FVG", "Studying BPR reactions and follow-through", "Identifying BPR on Any Timeframe", "BPR + OB Confluence", "Partial BPR Fills and Continuation"],
    isNew: true,
  },
  {
    id: 27, module: "35", title: "Execution & Trade Management", level: "Advanced", tag: "ICT",
    lessons: 7, duration: "65 min", emoji: "⚡", image: "/modules/module-27.webp",
    desc: "Study execution, stop placement, targets, partials, break-even logic, and position sizing within a defined trade plan.",
    topics: ["Entry Precision — Limit vs Market Orders", "Stop Loss Placement Logic", "Take Profit at Liquidity Targets", "Partial Profits — When and How Much", "Break Even Logic and Trail Stops", "Position Sizing and Risk Per Trade", "The Psychology of Execution"],
    isNew: true,
  },
  {
    id: 28, module: "36", title: "Backtesting & Model Development", level: "Advanced", tag: "ICT",
    lessons: 6, duration: "60 min", emoji: "🔬", image: "/modules/module-28.webp",
    desc: "Learn how to backtest an ICT model, evaluate sample size and out-of-sample behavior, and validate rules before risking capital.",
    topics: ["Why systematic backtesting is often neglected", "Setting Up a Proper Backtesting Environment", "What to Record in Every Backtest", "Sample Size and Statistical Uncertainty", "Turning Results Into a Defined Model", "Forward Testing Your Model on Demo"],
    isNew: true,
  },
  {
    id: 101, module: "06", title: "Risk Management: Core Principles", level: "Beginner", tag: "ICT",
    lessons: 5, duration: "18 min", emoji: "🛡️", image: "/modules/module-03.webp",
    desc: "Five core risk-management topics to study in ICT-style trading. Position sizing formula, R:R ratios, stop loss placement, loss limits, and the daily checklist that protects your account.",
    topics: ["Capital preservation as a core risk-management principle", "Position Sizing Formula", "The Risk-Reward Ratio", "Stop Loss Placement", "Daily, Weekly & Monthly Loss Limits"],
    isNew: true,
  },
  {
    id: 102, module: "19", title: "Advanced Position Sizing & Portfolio Heat", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "22 min", emoji: "📐", image: "/modules/module-04.webp",
    desc: "Master portfolio heat, correlated pairs, scaling in and out, and the Kelly Criterion. An advanced risk layer for studying exposure, correlation, scaling, and position sizing across multiple positions.",
    topics: ["Portfolio Heat: Total Account Exposure", "Correlated Pairs: Hidden Risk", "Scaling In and Out of Positions", "The Kelly Criterion for Optimal Risk", "Risk Management Checklist"],
    isNew: true,
  },
  {
    id: 103, module: "20", title: "The Psychology of Risk", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "20 min", emoji: "🧠", image: "/modules/module-05.webp",
    desc: "Study trading psychology, cognitive biases, discipline, mindset, and routines while testing which practices improve your own process.",
    topics: ["The Four Deadly Emotions", "Cognitive Biases in Trading", "Building Trading Discipline", "The Winning Mindset", "Creating Your Trading Routine"],
    isNew: true,
  },
  {
    id: 29, module: "05", title: "Risk Management Fundamentals", level: "Beginner", tag: "ICT",
    lessons: 5, duration: "18 min", emoji: "🛡️", image: "/modules/module-01.webp",
    desc: "Study core risk-management concepts including position sizing, R:R, stop placement, and loss limits before trading real capital.",
    topics: ["Why Risk Management Beats Strategy", "The 1% Rule & When to Break It", "Risk-to-Reward Ratio Explained", "Stop Loss Placement for ICT", "Daily, Weekly & Monthly Loss Limits"],
    isNew: true,
  },
  {
    id: 30, module: "21", title: "Advanced Risk Management & Position Sizing", level: "Intermediate", tag: "ICT",
    lessons: 5, duration: "22 min", emoji: "📐", image: "/modules/module-02.webp",
    desc: "Go beyond the basics — Kelly Criterion, correlation risk, drawdown recovery, and the psychology of protecting capital like a professional trader.",
    topics: ["The Kelly Criterion for ICT Traders", "Correlation Risk: The Hidden Account Killer", "Drawdown Recovery Strategies", "Position Sizing for Different Account Sizes", "The Psychology of Risk"],
    isNew: true,
  },
  {
    id: 201, module: "22", title: "ICT for NAS100 & US30 (Indices)", level: "Intermediate", tag: "ICT",
    lessons: 4, duration: "28 min", emoji: "📈", image: "/modules/module-09.webp",
    desc: "Study how traders adapt ICT concepts, session timing, opening ranges, and position sizing to NAS100 and US30.",
    topics: ["How ICT concepts may be adapted to indices", "NAS100 vs US30: Key Differences", "The Index Opening Range Strategy", "Index-Specific Risk Management"],
    isNew: true,
  },
  {
    id: 202, module: "23", title: "ICT for Gold (XAU/USD)", level: "Intermediate", tag: "ICT",
    lessons: 3, duration: "24 min", emoji: "🥇", image: "/modules/module-10.webp",
    desc: "Study what drives gold, how to adapt ICT killzones, and how traders apply ICT concepts to XAU/USD.",
    topics: ["What Drives Gold Prices", "Gold-Specific ICT Adaptations", "Gold volatility and safe-haven context"],
    isNew: true,
  },
  {
    id: 301, module: "24", title: "ICT for Crypto: Bitcoin & Ethereum", level: "Intermediate", tag: "ICT",
    lessons: 4, duration: "22 min", emoji: "₿", image: "/modules/module-11.webp",
    desc: "Apply ICT concepts to 24/7 crypto markets. Learn how traders adapt session timing, leverage controls, Bitcoin cycle context, and liquidity analysis to crypto.",
    topics: ["Applying ICT Concepts to Crypto", "Adapting Session Timing for Crypto", "Crypto-Specific Risk Management", "Bitcoin Cycle Context"],
    isNew: true,
  },
  {
    id: 31, module: "37", title: "Trade Review & Journal Process", level: "Advanced", tag: "PROCESS",
    lessons: 6, duration: "58 min", emoji: "📝", image: "/modules/module-27.webp",
    desc: "Turn completed trades into usable evidence with structured journaling, review metrics, screenshots and rule refinement.",
    topics: ["What to Record Before Entry", "Screenshot & Context Standards", "R-Multiple, MAE & MFE", "Setup Tagging & Error Taxonomy", "Weekly Performance Review", "Turning Data Into One Rule Change"],
    isNew: true,
  },
  {
    id: 32, module: "38", title: "Macro, News & Execution Risk", level: "Advanced", tag: "RISK",
    lessons: 5, duration: "46 min", emoji: "🗞️", image: "/modules/module-28.webp",
    desc: "Build a news-aware execution process that accounts for volatility, spreads, slippage, scheduled events and no-trade conditions.",
    topics: ["Reading the Economic Calendar", "Event Volatility & Scenario Planning", "Spread, Slippage & Fast Markets", "When to Stand Aside", "Building a News-Aware Trading Plan"],
    isNew: true,
  },

]

export const CURRICULUM_STATS = {
  moduleCount: MODULES.length,
  lessonCount: MODULES.reduce((total, module) => total + module.lessons, 0),
};
